version: "3"
services:
  mockbucket:
    build:
      context: .
    image: opendevstack/mockbucket:lastest
    ports:
      - "8080:8080"
    environment:
      BASIC_USERNAME: "myuser"
      BASIC_PASSWORD: "mypassword"
      REPOS: "opendevstack/ods-core.git;opendevstack/ods-quickstarters.git"
      VERBOSE: "true"
